### ISSUE TITLE
Outliers app not working

### ISSUE THREAD

**Issue by pshanmugathas** [derekbeaton/ONDRIApps#1]
@ahnjedid @derekbeaton 

Hi Jed,

My team members and I have tried to use the most recently updated Outliers app and it does not seem to generate PDFs or spreadsheets for the data packages that we've tried. Below is the error message I get when trying to download the results.

![image](https://user-images.githubusercontent.com/56092651/71826152-4c6bf980-306b-11ea-8a49-47c8f2e185ff.png) 

Thank you,
Priya

**Comment by ahnjedid** [comment]
Hi Priya,

It seems like there are issues with the RMarkdown code template which is causing this error. I reverted the repository to the most previous working copy so your team can run Outliers while Derek and I handle this issue. 

Cheers,
Jed

**Comment by ahnjedid** [comment]
Outliers App has been fully revamped. Change log:

- PDF reports generated only. HTML report option removed.
- PDF report can be saved in folder of choice only when the app is run in a browser (not a window).
- App no longer crashes when there are insignificant outliers. Previous code would create a data frame if the vector created for each participant was the same length, when we needed a list of vectors.
- Fixed bug that wasn't adding subject IDs to variable rankings. plyr::alply function default removes row names.

Issue resolved and closed.
