### ISSUE TITLE
Issue generating reports

### ISSUE THREAD

**Issue by desoura** [derekbeaton/ONDRIApps#3]
@ahnjedid 
Hi Jed, 

The team has been having some trouble generating Outliers reports for a few packages. The app crashes when we hit the "Generate Report" button. The data that seems to cause the crash have some similarities: 
- The data produces **no "significant outliers"** in the **GMCD** step (even when Bootstrap Cutoff values are set to the minimum):
![image](https://user-images.githubusercontent.com/55763923/74765981-80cdfa80-5252-11ea-87cb-aab7b84b5f1f.png)
- The **CorrMax** plot just has lines running through it with no variable/participant names:
![image](https://user-images.githubusercontent.com/55763923/74766085-b4108980-5252-11ea-95d8-7f197697a229.png)
- The **error message** looks like the following: 
![image](https://user-images.githubusercontent.com/55763923/74766176-ddc9b080-5252-11ea-9101-f419e75796b4.png)

A couple of packages that do this are the **OND01_ADMCI_06_CLIN_PSQI_2020FEB12**, **OND01_ALS_04_CLIN_QIDS_2020FEB12**, and **OND01_FTD_04_CLIN_PSQI_2020FEB12** packages. 
I think our previous strategy to get around this was to just generate the report at the Ordination step. 

Thanks, 

Roland

**Comment by derekbeaton** [comment]
Please report this in our Gitlab repos in BrainCODE.
